S02 mt32 index
WildCodeSchool-2024-02/PHP-REM-POEC-05-MidiATech pull request #18
Opened 2024-07-25 07:34 UTC by RomainGuirous

2024-07-25 11:26 UTC, naima0783 requested changes

2024-07-25 11:26 UTC, naima0783 commented on public/assets/javascript/home.js
> +console.log(img);
le console log est normal ici ?

2024-07-25 12:18 UTC, styvens-w commented on public/assets/javascript/home.js
> +console.log(img);
il faut supprimer le console.log

2024-07-25 12:24 UTC, styvens-w requested changes
À corriger les petites erreurs

2024-07-25 12:24 UTC, styvens-w commented on public/assets/images/chainsaw.jpg
Les images sont encore utiles ?

2024-07-25 12:24 UTC, styvens-w commented on public/assets/images/echoes_of_the_eye.jpg
Les images sont encore utiles ?

2024-07-25 12:24 UTC, styvens-w commented on public/assets/images/link-faces-of-evil-loli.png
Les images sont encore utiles ?

2024-07-25 13:15 UTC, RomainGuirous commented on public/assets/javascript/home.js
> +console.log(img);
j'ai retiré

2024-07-25 13:16 UTC, RomainGuirous commented on public/assets/images/chainsaw.jpg
je pense qu'il faut peaufiner encore
je n'ai pas vu si des images avaient déjà été implantées, mais en attendant c'est mieux que rien

2024-07-25 13:20 UTC, styvens-w commented on public/assets/images/chainsaw.jpg
oui, pour les images, c'est directement des liens, et si pas d'image, les images part deja, tu peut voir comment c'est dans Media/index.html.show

2024-07-25 15:26 UTC, GuillaumeCregut requested changes

2024-07-25 15:26 UTC, GuillaumeCregut commented on public/assets/css/home.css
> +
Code mort

2024-07-26 07:49 UTC, styvens-w approved these changes

2024-07-26 07:50 UTC, styvens-w approved these changes

2024-07-26 08:04 UTC, GuillaumeCregut approved these changes

2024-07-26 08:05 UTC, naima0783 approved these changes

2024-07-26 08:05 UTC, merged