Demo
WildCodeSchool-2024-02/PHP-REM-POEC-05-MidiATech pull request #24
Opened 2024-08-04 12:50 UTC by naima0783

correction erreur , plus ajout responsive, modif home

2024-08-04 12:53 UTC, styvens-w approved these changes

2024-08-04 16:39 UTC, RomainGuirous approved these changes

2024-08-05 07:28 UTC, GuillaumeCregut requested changes

2024-08-05 07:28 UTC, GuillaumeCregut commented on src/Controller/BooksController.php
> +    public function show($id): string
Pourquoi avoir supprimer le typage ?

2024-08-05 07:44 UTC, naima0783 reviewed
corrigé

2024-08-05 07:46 UTC, naima0783 reviewed
correction ci

2024-08-05 07:55 UTC, GuillaumeCregut approved these changes

2024-08-05 07:55 UTC, merged